"""Create career analyses table

Revision ID: 3be0f1a4006d
Revises: f29a0bf14cac
Create Date: 2026-09-13 11:02:00.787845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3be0f1a4006d'
down_revision: Union[str, Sequence[str], None] = 'f29a0bf14cac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('career_goal', sa.String(length=100), nullable=False),
    sa.Column('suitability', sa.String(length=20), nullable=False),
    sa.Column('career_readiness_score', sa.Integer(), nullable=False),
    sa.Column('resume_score', sa.Integer(), nullable=False),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('skill_gaps', sa.Text(), nullable=True),
    sa.Column('recommended_skills', sa.Text(), nullable=True),
    sa.Column('recommended_projects', sa.Text(), nullable=True),
    sa.Column('roadmap', sa.Text(), nullable=True),
    sa.Column('profile_resume_match', sa.Text(), nullable=True),
    sa.Column('resume_summary', sa.Text(), nullable=True),
    sa.Column('resume_strengths', sa.Text(), nullable=True),
    sa.Column('resume_missing_skills', sa.Text(), nullable=True),
    sa.Column('resume_improvement_suggestions', sa.Text(), nullable=True),
    sa.Column('resume_recommended_projects', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_analyses_id'), 'career_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_career_analyses_user_id'), 'career_analyses', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_career_analyses_user_id'), table_name='career_analyses')
    op.drop_index(op.f('ix_career_analyses_id'), table_name='career_analyses')
    op.drop_table('career_analyses')
    # ### end Alembic commands ###
