"""Add GitHub username to user profile

Revision ID: 69767b17b73b
Revises: 3be0f1a4006d
Create Date: 2026-09-24 09:51:08.043362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69767b17b73b'
down_revision: Union[str, Sequence[str], None] = '3be0f1a4006d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('github_username', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'github_username')
    # ### end Alembic commands ###
